version: '3'

services:
  publicweb:
    image: publicweb
    build:
      context: .
      dockerfile: PublicWeb\Dockerfile

  adminweb:
    image: adminweb
    build:
      context: .
      dockerfile: AdminWeb\Dockerfile

