version: '3'

services:
  publicweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  adminweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

